"""empty message

Revision ID: 4b23175cbb48
Revises:
Create Date: 2025-09-23 17:25:12.990293

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4b23175cbb48"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=15), nullable=False),
        sa.Column("surname", sa.String(length=15), nullable=False),
        sa.Column("age", sa.Integer(), nullable=False),
        sa.Column("hobbies", sa.String(length=100), nullable=False),
        sa.Column(
            "relationship_status",
            sa.Enum("single", "in relationship", "married", name="relationshipstatus"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
